<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>Chess4D.Engine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(PackagesRoot)com.chess4d.engine/Runtime/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Chess4D.Core/Chess4D.Core.csproj" />
  </ItemGroup>
</Project>
