<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Chess4D.Core/Chess4D.Core.csproj" />
    <ProjectReference Include="../Chess4D.Engine/Chess4D.Engine.csproj" />
    <ProjectReference Include="../Chess4D.Tablebase/Chess4D.Tablebase.csproj" />
  </ItemGroup>
</Project>
