<Project>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackagesRoot>$(MSBuildThisFileDirectory)../Packages/</PackagesRoot>
  </PropertyGroup>
</Project>
